# https://taskfile.dev/usage/
version: '3'

vars:
  VENV_DIR: ./venv

env:
  PIP_INDEX_URL: https://mirrors.ustc.edu.cn/pypi/web/simple

tasks:
  default:
    desc: create virtual environments
    deps:
      - venv
    cmds:
      - "{{.VENV_DIR}}/bin/pip install --upgrade pip"
      - "{{.VENV_DIR}}/bin/pip install -r requirements.txt"
      - touch {{.VENV_DIR}}
      - echo "use [\$source venv/bin/activate] to activate virtual environment"
    status:
      - test {{.VENV_DIR}} -nt requirements.txt

  venv:
    desc: create virtual environments
    cmds:
      - python3 -m venv {{.VENV_DIR}}
    status:
      - test -d {{.VENV_DIR}}

  test:maven-project-single-module:
    desc: single module maven project
    cmds:
      - python spring_initializr_cli.py -f --config-file=templates/maven-project-single-module.yaml outputs

  test:gradle-groovy-single-module:
    desc: single module gradle groovy project
    cmds:
      - python spring_initializr_cli.py -f --config-file=templates/gradle-project-single-module.yaml outputs
